# Generated by Django 5.1.2 on 2025-05-22 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=datetime.date(2025, 5, 22)),
        ),
    ]
