# Generated by Django 4.2.21 on 2025-05-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
